const sampleProducts = [
  {
    reference_title: "School Fees Loan",
    interest_calculation_type: "flat",
    base_percentage: "10.0000",
    fine_rules: { penalty_after_days: 30 },
    min_loan_amount: "1000.00",
    max_loan_amount: "50000.00",
    max_term_days: 120,
  },
  {
    reference_title: "Emergency Loan",
    interest_calculation_type: "reducing_balance",
    base_percentage: "15.0000",
    fine_rules: { automated_reminders: true },
    min_loan_amount: "100.00",
    max_loan_amount: "5000.00",
    max_term_days: 30,
  },
  {
    reference_title: "Agri-Business Growth Loan",
    interest_calculation_type: "flat",
    base_percentage: "8.5000",
    fine_rules: { penalty_after_days: 60 },
    min_loan_amount: "5000.00",
    max_loan_amount: "200000.00",
    max_term_days: 270,
  },
  {
    reference_title: "SME Asset Financing",
    interest_calculation_type: "reducing_balance",
    base_percentage: "12.0000",
    fine_rules: { grace_period_days: 7 },
    min_loan_amount: "10000.00",
    max_loan_amount: "500000.00",
    max_term_days: 365,
  },
  {
    reference_title: "Eco-Green Solar Loan",
    interest_calculation_type: "flat",
    base_percentage: "5.0000",
    fine_rules: { grace_period_days: 14, charge_fixed_late_fee: true },
    min_loan_amount: "250.00",
    max_loan_amount: "7500.00",
    max_term_days: 180,
  },
];
